version: '3.8'

services:
  chatbot-api:
    build: ..
    ports:
      - "5008:5008"
    environment:
      - FLASK_ENV=development
    container_name: chatbot-api
    networks:
      - abc-call-network

networks:
  abc-call-network:
    external: true