name: Integration
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      # - name: Run tests
      #   run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  merge-branches:
    name: Merge Main into Develop and Develop into Main
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'terminada') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge main into develop
        uses: tukasz/direct-merge-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: main
          target-branch: develop
          merge-method: no-ff

      - name: Merge develop into main
        uses: tukasz/direct-merge-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: main
          merge-method: no-ff